version: "3.9" # Docker Compose のバージョン指定

services:
  db: # データベース(PostgreSQL)の定義
    image: postgres # PostgreSQLイメージ
    volumes:
      - ./tmp/db:/var/lib/postgresql/data # ホスト側の ./tmp/db をDBデータ保存先にマウント
    environment:
      POSTGRES_PASSWORD: password # DBのパスワード設定（開発用のため平文でもOK）

  web: # Railsアプリケーション用のサービス
    build:
      context: . # ビルドコンテキスト（Dockerfileのある場所）
      dockerfile: ./docker/Dockerfile # 使用するDockerfileのパス
    command:
      bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
      # Rails起動コマンド。前回起動時に残ったPIDファイルを削除してからサーバー起動。
    volumes:
      - .:/myapp # 現在のディレクトリをコンテナ内の /myapp にマウント（ソースコード反映のため）
    ports:
      - "3000:3000" # ホストの3000番ポートをコンテナの3000番ポートにマッピング
    depends_on:
      - db # dbサービス（PostgreSQL）が起動してからwebサービスを起動
    env_file:
      - .env # 環境変数を外部の .env ファイルから読み込む
