services:
  - type: web
    name: my-rails-app
    env: docker
    plan: free
    autoDeploy: true

    envVars:
      - key: DATABASE_URL
        value: <%= ENV["DATABASE_URL"] %>
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
