default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

# development:
#   <<: *default
#   database: myapp_development

development:
  <<: *default
  host: <%= ENV["DB_HOST"].sub(/^@/, '') %>
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  sslmode: require

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  host: <%= ENV["DB_HOST"].sub(/^@/, '') %>
  database: <%= ENV["DB_NAME"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
  sslmode: require
