name: Deploy to Render

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          set -e
          echo "Triggering Render deploy for service: $RENDER_SERVICE_ID"
          resp=$(curl -s -o /dev/stderr -w "%{http_code}" \
            -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"clearCache":false}' \
            "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys")
          if [ "$resp" -ge 200 ] && [ "$resp" -lt 300 ]; then
            echo "Render deploy triggered successfully (status: $resp)"
          else
            echo "Failed to trigger Render deploy (status: $resp)" >&2
            exit 1
          fi
