name: Deploy to Render

on:
  push:
    branches: [main, docker-compose-fix]
  workflow_dispatch: {}

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ttskch/render-deploy@v1.0.0
        with:
          api-key: ${{ secrets.RENDER_API_KEY }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          interval: 20
          timeout: 300
