name: Deploy to Render

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          set -e
          echo "Triggering Render deploy for service: $RENDER_SERVICE_ID"

          # Renderにデプロイをリクエスト
          response=$(curl -s -w "\n%{http_code}" \
            -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"clearCache":false}' \
            "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys")

          # HTTPコードとレスポンス本体を分離
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')

          if [ "$http_code" -ge 200 ] && [ "$http_code" -lt 300 ]; then
            echo "✅ Render deploy triggered successfully (status: $http_code)"
            echo "$body"
          else
            echo "❌ Failed to trigger Render deploy (status: $http_code)"
            echo "$body"
            exit 1
          fi
